id: P624A6B44
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: pt
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    a54e83bd2f154d0eb127cfa19a101621:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    bbb94658f1f94ee09054c976adbb91bd:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    ffb3ad78400a4ce993007af50dc04d24:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    e891eb93e8514e98baba2ebb9d3d1f32:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    de2320af26844890be882b9f4fb9d223:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.801121'
last_modified_at: '2022-03-01T02:52:02.801124'
